### ISSUE TITLE
Trying to run PGI but missing file configs/tpu_utils

### ISSUE THREAD

**Issue by joangog** [vihari/CGD#1]
Hi! I am trying to reproduce your paper as part of a project in my course at University of Amsterdam and I am trying to follow your instructions to run the PGI model using WILDS. However there is a missing file that is imported in PGI.py at "from configs import tpu_utils". I cannot seem to find it in the WILDS repo. It is used at "tpu_utils.mark_step()" at line 53 but I do not understand its function or if it can simply be removed. Can you please point me towards the right direction?

**Comment by vihari** [comment]
It is the same as optimizer.step(). If you are not using tpu, please just replace it by `optimizer.step()`. Thanks for pointing the issue.

**Comment by joangog** [comment]
Thanks!!
